<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link href="[{#s_base#}]/dbfacephp/css/style-default.css" rel="stylesheet" type="text/css"><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/prototype.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/jquery.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/tommick.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/Utils.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/rview.js"></script><script type="text/javascript">
    $j(document).ready(function() {
     $j("input.config-textfield").attr('style', 'border:2px solid #DFDFDF');
     $j("input.config-textfield").blur(function() {
       $j(this).attr('style', 'border:2px solid #DFDFDF');
     }).focus(function() {
       $j(this).attr('style', 'border:2px solid #DFD77D');
     });
     $j('#username').focus();
    });
    function createaccount() {
      $('mainForm').request({
        method: 'post',
        onComplete: function(transport){ 
          $('error').update(transport.responseText+"<img src='"+STATIC_URL+"/img/close.gif' onclick='javascript:hideElement(\"error\")' style='float:right;cursor:pointer'>").show(); 
        } 
      });
    }
  </script></head><body><div id="bodyColumn"><div id="navcolumn"><a href="[{#dbfacephp_base_url#}]/index.php?c=home&m=dashboard">[{ci_lang key='strDashboard'}]</a> ><a href="[{#dbfacephp_base_url#}]/index.php?c=conn&m=listconn">[{ci_lang key='strAdministration'}]</a> > Create new account</div><form action="[{#dbfacephp_base_url#}]/index.php?c=register" method="post" id='mainForm' name='mainForm'><input type="hidden" name="action" value="submit"><div id="error" style="display:none"></div><table border="0" cellpadding="0" cellspacing="0" id="connTable" class="otherDisplay2"><tr><td colspan=3><b>Create a new account and setup the permissions.</b></td></tr><tr><td colspan="3"><fieldset><legend>Login Information</legend><table width="90%" cellspacing="0" cellpadding="0" align="left" style="border:0"><tr><td width="20%" height="30" nowrap class="bodyTextBold">Username:</td><td width="70%" height="18"><input name="username" id="username" type="text" class="config-textfield" value="[{$username}]" size="30"></td><td width="10" height="30">&nbsp;</td></tr><tr><td width="20%" height="30" nowrap class="bodyTextBold">Password:</td><td width="70%" height="30"><input name="password" type="password" class="config-textfield" id="password" name="password" value="" size="30"><br/></td><td width="10" height="30">&nbsp;</td></tr><tr><td width="20%" height="30" nowrap class="bodyTextBold">Confirm Password:</td><td width="70%" height="30"><input name="password2" type="password" class="config-textfield" id="password2" name="password2" value="" size="30"><br/></td><td width="10" height="30">&nbsp;</td></tr><tr><td width="20%" height="30" nowrap class="bodyTextBold">Permission:</td><td width="70%" height="30"><ul id="stylelist"><li><input type="radio" name="role" id="role_user" value="user" checked><label for="role_user">General user on all existing connections</label></li><li><input type="radio" name="role" id="role_admin" value="administrator"/><label for="role_admin">Administrator on all existing connections</label></li><li><input type="radio" name="role" id="role_none" value="administrator"/><label for="role_none">I will setup the permission later</label></li></ul></td><td width="10" height="30">&nbsp;</td></tr></table></fieldset></td></tr><tr style="margin-top:5px;margin-bottom:5px"><td style="text-align:center" valign="bottom" colspan=3><input type="button" class="input-submit" value="Create" onclick="javascript:createaccount();"/><input type="button" class="input-submit gray" onclick="javascript:document.location='[{#dbfacephp_base_url#}]/index.php?c=conn&m=listconn'" value="Cancel"/></td></tr></table></form></div></body></html>