<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link href="[{#s_base#}]/dbfacephp/css/style-default.css" rel="stylesheet" type="text/css"><link href="[{#s_base#}]/dbfacephp/css/colors-fresh.css" rel="stylesheet" type="text/css"><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/jquery.js"></script><script type="text/javascript">
    function loadingIFRAME(iframeID) {
      $j('#load'+iframeID).hide();
      $j('#iframe'+iframeID).css('visibility', 'visible');
    }
  </script></head><body id="bodyColumn" style="margin-left:5px"><div id="navcolumn"><a href="[{#dbfacephp_base_url#}]/index.php?c=home&m=dashboard">[{ci_lang key='strDashboard'}]</a> > [{$appname}]</div><div id="wpwrap"><div id="wpcontent"><div id="wpbody"><div id="wpbody-content"><div class="wrap"><div id="dashboard-widgets-wrap"><div id='dashboard-widgets' class='metabox-holder'> [{section name=i loop=$layout}] <div class='postbox-container' style='[{if $layout[i].fullwidth == 1}]width:98%[{else}]width:49%[{/if}];'><div id='normal-sortables' class='meta-box-sortables'> [{section name=j loop=$layout[i].apps}] <div class="postbox"><div class="handlediv" title="Click to toggle" onclick="javascript:$j('#div_inside_[{$smarty.section.i.index}]_[{$smarty.section.j.index}]').slideToggle('fast');"><br/></div> [{if $layout[i].minimized == 1}] <script type="text/javascript">
          $j(document).ready(function() {
            $j('#div_inside_[{$smarty.section.i.index}]_[{$smarty.section.j.index}]').slideToggle('fast');
          });
        </script> [{/if}] <h3 class='hndle'><span>[{$layout[i].apps[j].appname}]</span></h3><div class="inside" style="align:center" id="div_inside_[{$smarty.section.i.index}]_[{$smarty.section.j.index}]"><div id="load[{$smarty.section.i.index}]_[{$smarty.section.j.index}]" style="text-align:center;valign:middle"><img src="[{#s_base#}]/dbfacephp/img/iframe-loader.gif" alt="Application Loading..."/></div><iframe onload="javascript:loadingIFRAME('[{$smarty.section.i.index}]_[{$smarty.section.j.index}]');" id="iframe[{$smarty.section.i.index}]_[{$smarty.section.j.index}]" style="margin-left:auto;margin-right:auto;visibility:hidden;border: 0px solid #ffffff;framespacing:0px;width:100%;min-height:300px" frameborder="0" src="[{#dbfacephp_base_url#}]/index.php?c=app&appid=[{$layout[i].apps[j].appid}]&iframe=true"></iframe></div></div> [{/section}] </div></div> [{/section}]
</div></div></div></div></div></div></div></body></html>