<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link href="[{#s_base#}]/dbfacephp/css/style-default.css" rel="stylesheet" type="text/css"><link href="[{#s_base#}]/dbfacephp/css/colors-fresh.css" rel="stylesheet" type="text/css"><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/prototype.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/jquery.js"></script><script type="text/javascript">
  function create_dashboard_app() {
    var dapps = $j("#sidebar-1").find("._wpnonce_widgets");
    var appids = "";
    for(var i=0; i<dapps.length;i++) {
      appids += "&dappid[]="+dapps[i].value;
    }
    var fullwidth = "";
    var dfullwidths = $j("#sidebar-1").find("._widgets_fullwidth");
    for(var i=0; i<dfullwidths.length;i++) {
      fullwidth += "&fullwidth[]="+(dfullwidths[i].checked ? 1 : 0);
    }
    var minimized = "";
    var dminimizeds = $j("#sidebar-1").find("._widgets_minimized");
    for(var i=0; i<dminimizeds.length;i++) {
      minimized += "&minimized[]="+(dminimizeds[i].checked ? 1 : 0);
    }
    document.mainForm.action.value='create';
    new Ajax.Request('[{#dbfacephp_base_url#}]/index.php?c=create&m=dashboard', {
       method: 'post',
       parameters: $('mainForm').serialize()+appids+fullwidth+minimized,
       onSuccess: function(transport) {
         $('js_error').update(transport.responseText).show();
         document.body.scrollTop = 0;
         
         window.parent.frames['menu'].document.location.reload();
         setCookie('NavAccordion', 'false|true|false');         
       }
     });    
  }
</script></head><body id="bodyColumn" style="margin-left:5px"><div id="navcolumn"><a href="[{#dbfacephp_base_url#}]/index.php?c=home&m=dashboard">[{ci_lang key='strDashboard'}]</a> > [{ci_lang key='strApplicationManagement'}]</div><div id="js_error" class="js_success" style="display:none"></div><form name="mainForm" id="mainForm" method="POST"><input type="hidden" name="appid" value="[{$appid}]"/><input type="hidden" name="appname" value="[{$appname}]"/><input type="hidden" name="apptitle" value="[{$apptitle}]"/><input type="hidden" name="appdesc" value="[{$appdesc}]"/><input type="hidden" name="apptype" value="5"/> [{if $update}]<input type="hidden" name="update" value="1"/>[{/if}]
</form><div id="wpwrap"><div id="wpcontent"><div id="wpbody"><div id="wpbody-content"><div class="wrap"><table cellspacing="0" cellpadding="0" style="border:0;"><tr><td style="width:300px"><div class="widget-liquid-left"><div id="widgets-left"><div id="available-widgets" class="widgets-holder-wrap"><div class="sidebar-name"><div class="sidebar-name-arrow"><br/></div><h3>Available Applications</h3></div><div class="widget-holder" style="height:410px;overflow:auto"><p class="description">Drag applications from here to a dashboard on the right to activate them. Drag application back here to deactivate them and delete their settings.</p><div id="widget-list"> [{section name=i loop=$apps}] <div id='widget-1_archives-__i__' class='widget'><div class="widget-top"><div class="widget-title-action"><a class="widget-action hide-if-no-js" href="#available-widgets"></a><a class="widget-control-edit hide-if-js" href="#"></a></div><div class="widget-title"><h4>[{$apps[i].appname}]<span class="in-widget-title"></span></h4></div></div><div class="widget-inside"><form action="" method="post"><div class="widget-content"><p><input type="checkbox" class="_widgets_fullwidth" id="widget-archives-__i__-fullwidth" name="widget-archives-__i__-fullwidth" value="1" checked/><label for="widget-archives-__i__-fullwidth">Full Width</label><input type="checkbox" class="_widgets_minimized" id="widget-archives-__i__-minimized" name="widget-archives-__i__-minimized" value="1"/><label for="widget-archives-__i__-minimized">Minimized</label></p></div><input type="hidden" name="widget-id" class="widget-id" value="archives-__i__"/><input type="hidden" name="widget-width" class="widget-width" value="250"/><input type="hidden" name="widget-height" class="widget-height" value="200"/><input type="hidden" name="add_new" class="add_new" value="multi"/><input type="hidden" name="_wpnonce_widgets" class="_wpnonce_widgets" value="[{$apps[i].appid}]"/><div class="widget-control-actions"><div class="alignleft"><a class="widget-control-remove" href="#remove">Remove</a> |	<a class="widget-control-close" href="#close">Close</a><img src="[{#s_base#}]/dbfacephp/img/wpspin_light.gif" class="ajax-feedback " title="" alt=""/></div></div></form></div><div class="widget-description">[{$apps[i].appdesc}]</div></div> [{/section}] </div><br class='clear'/></div><br class="clear"/></div></div></div></td><td><div class="widget-liquid-right"><div id="widgets-right"><div class="widgets-holder-wrap"><div class="sidebar-name"><div class="sidebar-name-arrow"><br/></div><h3>Dashboard Application:[{$appname}]</h3></div><div id='sidebar-1' class='widgets-sortables' style="height:400px;overflow:auto">
[{section name=i loop=$layout}]
<div class="widget ui-draggable" id="widget-1_archives-[{$layout[i].appid}]" style="display: block;"><div class="widget-top"><div class="widget-title-action"><a href="#available-widgets" class="widget-action hide-if-no-js"></a><a href="#" class="widget-control-edit hide-if-js"></a></div><div class="widget-title"><h4>[{$layout[i].appname}]<span class="in-widget-title"></span></h4></div></div><div class="widget-inside" style="display: block;"><form method="post" action=""><div class="widget-content"><p><input type="checkbox" [{if $layout[i].fullwidth == "1"}]checked="checked"[{/if}] value="1" name="widget-archives-[{$layout[i].appid}]-fullwidth" id="widget-archives-[{$layout[i].appid}]-fullwidth" class="_widgets_fullwidth"><label for="widget-archives-[{$layout[i].appid}]-fullwidth">Full Width</label><input type="checkbox" [{if $layout[i].minimized == "1"}]checked="checked"[{/if}] value="1" name="widget-archives-[{$layout[i].appid}]-minimized" id="widget-archives-[{$layout[i].appid}]-minimized" class="_widgets_minimized"><label for="widget-archives-[{$layout[i].appid}]-minimized">Minimized</label></p></div><input type="hidden" value="archives-[{$layout[i].appid}]" class="widget-id" name="widget-id"><input type="hidden" value="250" class="widget-width" name="widget-width"><input type="hidden" value="200" class="widget-height" name="widget-height"><input type="hidden" value="" class="add_new" name="add_new"><input type="hidden" class="_wpnonce_widgets" name="_wpnonce_widgets" value="[{$layout[i].appid}]"><div class="widget-control-actions"><div class="alignleft"><a href="#remove" class="widget-control-remove">Remove</a> |	<a href="#close" class="widget-control-close">Close</a><img alt="" title="" class="ajax-feedback " src="[{#s_base#}]/dbfacephp/img/wpspin_light.gif" style="visibility: hidden;"></div></div></form></div><div class="widget-description">[{$layout[i].appdesc}]</div></div>
[{/section}] </div></div></div></div></td></tr><tr><td colspan="2" style="text-align:right"><hr/><input type="button" class="input-submit gray" value="<< [{ci_lang key='strBack'}]" onclick="javascript:document.location='[{#dbfacephp_base_url#}]/index.php?c=app&m=create_step1';"/><input type="button" class="input-submit" value="[{if $update}][{ci_lang key='strUpdate'}][{else}][{ci_lang key='strCreate'}][{/if}]" onclick="javascript:create_dashboard_app();"/></tr></table></div></div></div></div></div><script type='text/javascript' src="[{#s_base#}]/dbfacephp/js/jquery/hoverIntent.js"></script><script type='text/javascript' src="[{#s_base#}]/dbfacephp/js/jquery/ui.core.js"></script><script type='text/javascript' src="[{#s_base#}]/dbfacephp/js/jquery/ui.droppable.js"></script><script type='text/javascript' src="[{#s_base#}]/dbfacephp/js/jquery/ui.draggable.js"></script><script type='text/javascript' src="[{#s_base#}]/dbfacephp/js/jquery/ui.sortable.js"></script><script type='text/javascript' src="[{#s_base#}]/dbfacephp/js/widgets.js"></script>
[{include file="analytics.tpl"}] </body></html>