<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link href="[{#s_base#}]/dbfacephp/css/style-default.css" rel="stylesheet" type="text/css"><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/prototype.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/jquery.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/tommick.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/Utils.js"></script><script type="text/javascript" src="[{#s_base#}]/dbfacephp/js/rview.js"></script><script type="text/javascript">
    function deleteconnection() {
       if (!confirm("All data of the selected connection will be lost. Do you really want to delete the connection?\n\nPress OK to delete or press Cancel to return back.")) {
        return;
      }
    }
  </script></head><body><div id="bodyColumn"><div id="navcolumn"><a href="javascript:;">Settings</a> ><a href="javascript:;">My Connections</a></div><div id="error" style="display:none"></div><form action="[{#dbfacephp_base_url#}]/index.php?c=req&m=myconnections" method="post" id="mainForm" name="mainForm"> [{if $owner}] <table border="0" cellpadding="0" cellspacing="0" class="otherDisplay2"><tr><td class="config-label">Connections:</td><td><select id="dbid" name="dbid" class="config-picklist"> [{section name=i loop=$dbs}] <option value="[{$dbs[i].dbid}]" [{if $dbs[i].dbid == $dbid}]selected[{/if}]>[{$dbs[i].aliasname}]</option> [{/section}] </select><a href="[{#dbfacephp_base_url#}]/req/createconn"><img src="[{#s_base#}]/dbfacephp/img/add.gif" class="imgbtn" style="vertical-align:middle"/></a><img src="[{#s_base#}]/dbfacephp/img/delete20.gif" href="javascript:;" onclick="javascript:deleteconnection();" class="imgbtn" style="vertical-align:middle"/></td></tr><tr><td colspan="2" class="bodyText"><hr/></td></tr><tr><td class="config-label">Creator:</td><td id="creator">[{$creator}]</td></tr><tr><td colspan="2" class="bodyText"><hr/></td></tr><tr><td class="config-label">Access Users:</td><td><select MULTIPLE size=5 id="accessusers" name="accessusers" class="config-textarea" style="width:200px"> [{section name=i loop=$accessusers}] <option value="[{$accessusers[i].userid}]">[{$accessusers[i].accessuser}]</option> [{/section}] </select><img src="[{#s_base#}]/dbfacephp/img/user_delete.png" href="javascript:;" onclick="javascript:getFormList('formID');" class="imgbtn" style="vertical-align:bottom"/></td></tr><tr><td colspan="2" class="bodyText"><hr/></td></tr><tr><td class="config-label">Email:</td><td><input type="text" class="config-textfield" id="email" name="email" size="30" value="" autocomplete="off"/><script type="text/javascript">
            if (typeof(autoSug) == "undefined") {
              autoSug = new autoSuggest("email", {});
            }
          </script><input type="button" class="input-submit" value="Add"/><br/><span class="info-text">Enter the email account that you want to give access privilege to the selected connection. </span></td></tr></table> [{else}] <table border="0" cellpadding="0" cellspacing="0" class="otherDisplay2"><tr><td class="config-label">Connections:</td><td><select id="dbid" name="dbid" class="config-picklist"> [{section name=i loop=$dbs}] <option value="[{$dbs[i].dbid}]" [{if $dbs[i].dbid == $dbid}]selected[{/if}]>[{$dbs[i].aliasname}]</option> [{/section}] </select><img src="[{#s_base#}]/dbfacephp/img/delete20.gif" href="javascript:;" onclick="javascript:deleteconnection();" class="imgbtn" style="vertical-align:middle"/></td></tr><tr><td colspan="2" class="bodyText"><hr/></td></tr><tr><td class="config-label">Creator:</td><td id="creator">[{$creator}]</td></tr></table> [{/if}] </form><input type="button" class="input-submit" value="Create new connection" onclick="javascript:document.location='[{#dbfacephp_base_url#}]/index.php?c=req&m=createconn';"/></div></body></html>